// AUTO-GENERATED by src/scripts/build_catalogs.ts — do not edit by hand.
import type { JournalBehavior } from "../schemas/journal.js";

export const BEHAVIORS: readonly JournalBehavior[] = [
  {
    "behavior_tracker_id": 1,
    "title": "Alcohol",
    "question": "Have any alcoholic drinks?",
    "internal_name": "alcohol",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 2,
    "title": "Caffeine",
    "question": "Consumed caffeine?",
    "internal_name": "caffeine",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 3,
    "title": "Marijuana",
    "question": "Used marijuana?",
    "internal_name": "marijuana",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 4,
    "title": "Sexual Activity",
    "question": "Engaged in sexual activity?",
    "internal_name": "sexual-activity",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 5,
    "title": "Tobacco",
    "question": "Used tobacco in any form?",
    "internal_name": "tobacco",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 6,
    "title": "Late Meal",
    "question": "Ate food close to bedtime?",
    "internal_name": "late-meal",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 7,
    "title": "Air Travel",
    "question": "Traveled on a plane?",
    "internal_name": "air-travel",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 8,
    "title": "Device (e.g. Phone) in Bed",
    "question": "Viewed a screen device in bed?",
    "internal_name": "device-in-bed",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 9,
    "title": "Anti-Anxiety Medication",
    "question": "Took anti-anxiety medication?",
    "internal_name": "anti-anxiety-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 10,
    "title": "Anti-Inflammatory Drugs (e.g. Ibuprofen)",
    "question": "Took an anti-inflammatory drug (NSAIDs)?",
    "internal_name": "anti-inflammatory-drugs",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 11,
    "title": "Prescription Pain Medication",
    "question": "Took prescription pain medication?",
    "internal_name": "prescription-pain-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 12,
    "title": "Prescription Sleep Medication",
    "question": "Took prescription sleep medication?",
    "internal_name": "prescription-sleep-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 14,
    "title": "Meat",
    "question": "Consumed meat?",
    "internal_name": "meat",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 15,
    "title": "Paleo Diet",
    "question": "Following a paleo diet?",
    "internal_name": "paleo-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 16,
    "title": "Vegetarian Diet",
    "question": "Following a vegetarian diet?",
    "internal_name": "vegetarian-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 18,
    "title": "Acupuncture",
    "question": "Received acupuncture therapy?",
    "internal_name": "acupuncture",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 20,
    "title": "Cupping",
    "question": "Received cupping therapy?",
    "internal_name": "cupping",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 23,
    "title": "Massage Therapy",
    "question": "Received massage therapy?",
    "internal_name": "massage-therapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 24,
    "title": "Meditation",
    "question": "Meditated?",
    "internal_name": "meditation",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 25,
    "title": "Sensory Deprivation",
    "question": "Used a sensory deprivation tank?",
    "internal_name": "sensory-deprivation",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 26,
    "title": "Stretching",
    "question": "Spent time stretching?",
    "internal_name": "stretching",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 27,
    "title": "Blue-Light Blocking Glasses",
    "question": "Wore blue-light blocking glasses before bed?",
    "internal_name": "blue-light-blocking-glasses",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 28,
    "title": "Read in Bed",
    "question": "Read (non-screened device) while in bed?",
    "internal_name": "read-in-bed",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 31,
    "title": "Shared Bed",
    "question": "Shared your bed?",
    "internal_name": "shared-bed",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 32,
    "title": "Sleep Mask",
    "question": "Wore a sleep mask?",
    "internal_name": "sleep-mask",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 33,
    "title": "Sleep in Own Bed",
    "question": "Slept in the same bed as usual?",
    "internal_name": "same-bed",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 34,
    "title": "Sound Machine (e.g. white noise)",
    "question": "Listened to noise while asleep?",
    "internal_name": "sound-machine",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 35,
    "title": "CBD",
    "question": "Used CBD oil in any form?",
    "internal_name": "cbd",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 36,
    "title": "Magnesium Supplement",
    "question": "Took a magnesium supplement?",
    "internal_name": "magnesium-supplement",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 37,
    "title": "Melatonin",
    "question": "Took a melatonin supplement?",
    "internal_name": "melatonin",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 40,
    "title": "Injury",
    "question": "Have an injury or wound?",
    "internal_name": "injury",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 41,
    "title": "Sickness",
    "question": "Feeling sick or ill?",
    "internal_name": "sickness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 42,
    "title": "Parenting",
    "question": "Parenting an infant?",
    "internal_name": "parenting",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 43,
    "title": "Menstruation",
    "question": "Menstruating?",
    "internal_name": "menstruation",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 44,
    "title": "Nursing",
    "question": "Nursing?",
    "internal_name": "nursing",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 45,
    "title": "Pregnancy",
    "question": "Pregnant?",
    "internal_name": "pregnancy",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 46,
    "title": "Stress",
    "question": "Experienced stress?",
    "internal_name": "stress",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 48,
    "title": "Ice Bath",
    "question": "Took an ice bath?",
    "internal_name": "ice-bath",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 49,
    "title": "Cryotherapy",
    "question": "Used cryotherapy treatment?",
    "internal_name": "cryotherapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 50,
    "title": "Intermittent Fasting",
    "question": "Followed an intermittent fasting diet?",
    "internal_name": "intermittent-fasting",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 51,
    "title": "Ketogenic Diet",
    "question": "Followed a ketogenic diet?",
    "internal_name": "ketogenic-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 52,
    "title": "Sauna",
    "question": "Used a sauna?",
    "internal_name": "sauna",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 53,
    "title": "Steam Room",
    "question": "Used a steam room?",
    "internal_name": "steam-room",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 54,
    "title": "Masturbation",
    "question": "Masturbated?",
    "internal_name": "masturbation",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 55,
    "title": "Relationship Status",
    "question": "Single?",
    "internal_name": "relationship-status",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 56,
    "title": "COVID-19 Symptoms",
    "question": "Experiencing COVID-19 symptoms?",
    "internal_name": "covid-19-symptoms",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 57,
    "title": "Hydration",
    "question": "Hydrated sufficiently?",
    "internal_name": "hydration",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 58,
    "title": "CPAP Machine",
    "question": "Did you utilize a CPAP Machine?",
    "internal_name": "cpap-machine",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 59,
    "title": "Sleep at High Altitude",
    "question": "Did you sleep at Altitude?",
    "internal_name": "sleep-at-high-altitude",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 60,
    "title": "Caregiving",
    "question": "Cared for the health of another?",
    "internal_name": "caregiving",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 61,
    "title": "Ear Plugs",
    "question": "Wore ear plugs to bed?",
    "internal_name": "ear-plugs",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 62,
    "title": "Breathwork",
    "question": "Practiced breathwork?",
    "internal_name": "breathwork",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 63,
    "title": "Blood Pressure Medication",
    "question": "Took blood pressure medication?",
    "internal_name": "blood-pressure-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 64,
    "title": "Purpose",
    "question": "Felt a sense of purpose?",
    "internal_name": "purpose",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 65,
    "title": "Control",
    "question": "Felt you had control over your life?",
    "internal_name": "control",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 66,
    "title": "Efficacy",
    "question": "Felt you had the resources/skills needed to complete your daily goals?",
    "internal_name": "efficacy",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 67,
    "title": "COVID-19 Vaccination (Dose #1)",
    "question": "Received dose #1 of COVID-19 vaccination?",
    "internal_name": "covid-19-vaccination-dose-1",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 68,
    "title": "COVID-19 Vaccination (Dose #2)",
    "question": "Received dose #2 of COVID-19 vaccination?",
    "internal_name": "covid-19-vaccination-dose-2",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 69,
    "title": "Hyperbaric Chamber",
    "question": "Used a hyperbaric chamber?",
    "internal_name": "hyperbaric-chamber",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 70,
    "title": "Red Light Therapy",
    "question": "Received red light therapy?",
    "internal_name": "red-light-therapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 71,
    "title": "Physical Therapy",
    "question": "Received physical therapy?",
    "internal_name": "physical-therapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 72,
    "title": "Chiropractor",
    "question": "Visited the chiropractor?",
    "internal_name": "chiropractor",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 73,
    "title": "Weighted Blanket",
    "question": "Used a weighted blanket while sleeping?",
    "internal_name": "weighted-blanket",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 74,
    "title": "Nasal Strip",
    "question": "Wore a nasal strip while sleeping?",
    "internal_name": "nasal-strip",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 75,
    "title": "Humidifier",
    "question": "Used a humidifier while sleeping?",
    "internal_name": "humidifier",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 76,
    "title": "Dog in Bedroom",
    "question": "Had a dog in the room while sleeping?",
    "internal_name": "dog-in-bedroom",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 77,
    "title": "Cat in Bedroom",
    "question": "Had a cat in the room while sleeping?",
    "internal_name": "cat-in-bedroom",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 78,
    "title": "Nursing Infant",
    "question": "Nursing an infant?",
    "internal_name": "nursing-infant",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 79,
    "title": "Ovulation",
    "question": "Ovulating?",
    "internal_name": "ovulation",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 80,
    "title": "Bloating",
    "question": "Experienced bloating?",
    "internal_name": "bloating",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 81,
    "title": "Hot Flash During Sleep",
    "question": "Had a hot flash while sleeping?",
    "internal_name": "hot-flashes",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 82,
    "title": "Menstrual Cramps",
    "question": "Experiencing menstrual cramps?",
    "internal_name": "menstrual-cramps",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 83,
    "title": "Ramadan",
    "question": "Observing Ramadan?",
    "internal_name": "ramadan",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 84,
    "title": "Fruits and Vegetables",
    "question": "Consumed fruits and/or vegetables?",
    "internal_name": "fruits-and-veggies",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 85,
    "title": "Carbohydrates",
    "question": "Consumed carbohydrates?",
    "internal_name": "carbohydrates",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 86,
    "title": "Clean Eating",
    "question": "Avoided processed foods?",
    "internal_name": "clean-eating",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 87,
    "title": "Gluten-Free Diet",
    "question": "Following a gluten-free diet?",
    "internal_name": "gluten-free-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 88,
    "title": "Dairy",
    "question": "Consumed dairy?",
    "internal_name": "dairy",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 89,
    "title": "Protein",
    "question": "Consumed protein?",
    "internal_name": "protein",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 90,
    "title": "Added Sugar",
    "question": "Consumed added sugar?",
    "internal_name": "added-sugar",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 91,
    "title": "Fats",
    "question": "Consumed fats?",
    "internal_name": "fats",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 92,
    "title": "Emotional/Mental State",
    "question": "Felt emotionally and mentally stable?",
    "internal_name": "emotional-mental-state",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 93,
    "title": "Energy Level",
    "question": "Felt energized throughout the day?",
    "internal_name": "energy-level",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 94,
    "title": "Motivation",
    "question": "Felt motivated?",
    "internal_name": "motivation",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 95,
    "title": "Irritability",
    "question": "Felt Irritable?",
    "internal_name": "irritability",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 96,
    "title": "Therapy Session",
    "question": "Had a therapy session?",
    "internal_name": "therapy",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 97,
    "title": "Seasonal Allergies",
    "question": "Experienced seasonal allergies?",
    "internal_name": "seasonal-allergies",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 98,
    "title": "On-Call Shift",
    "question": "Worked an on-call shift?",
    "internal_name": "on-call-shift",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 99,
    "title": "Night Shifts",
    "question": "Worked the night shift?",
    "internal_name": "night-shifts",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 100,
    "title": "Work Late",
    "question": "Worked late?",
    "internal_name": "work-late",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 101,
    "title": "Jet Lag",
    "question": "Experienced jet lag?",
    "internal_name": "jet-lag",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 102,
    "title": "Work Commute",
    "question": "Commuted to work?",
    "internal_name": "work-commute",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 103,
    "title": "Chemotherapy",
    "question": "Received chemotherapy?",
    "internal_name": "chemotherapy",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 104,
    "title": "Creatine",
    "question": "Took creatine?",
    "internal_name": "creatine",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 105,
    "title": "Fish Oil",
    "question": "Took fish oil?",
    "internal_name": "fish-oil",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 106,
    "title": "Multivitamin",
    "question": "Took a multivitamin?",
    "internal_name": "multivitamin",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 107,
    "title": "Probiotic",
    "question": "Took a probiotic?",
    "internal_name": "probiotic",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 108,
    "title": "Turmeric",
    "question": "Took turmeric?",
    "internal_name": "turmeric",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 109,
    "title": "Vitamin B-12",
    "question": "Took vitamin B-12?",
    "internal_name": "vitamin-b-12",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 110,
    "title": "Vitamin C",
    "question": "Took vitamin C?",
    "internal_name": "vitamin-c",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 111,
    "title": "Vitamin D",
    "question": "Took vitamin D?",
    "internal_name": "vitamin-d",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 112,
    "title": "COVID-19 Vaccination (Booster)",
    "question": "Received booster of COVID-19 vaccination?",
    "internal_name": "covid-19-vaccination-booster",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 113,
    "title": "Kosher Diet",
    "question": "Following a kosher diet?",
    "internal_name": "kosher-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 114,
    "title": "Dairy-Free Diet",
    "question": "Following a dairy-free diet?",
    "internal_name": "dairy-free-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 115,
    "title": "Vegan Diet",
    "question": "Following a vegan diet?",
    "internal_name": "vegan-diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 116,
    "title": "Gratitude",
    "question": "Expressed gratitude?",
    "internal_name": "gratitude",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 117,
    "title": "Work Calls",
    "question": "Spent time on work video calls?",
    "internal_name": "work-calls",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 118,
    "title": "Remote Work",
    "question": "Worked from home?",
    "internal_name": "remote-work",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 119,
    "title": "Journaling",
    "question": "Journaled your thoughts?",
    "internal_name": "journaling",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 120,
    "title": "Outdoor Time",
    "question": "Spend time outdoors?",
    "internal_name": "outdoor-time",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 121,
    "title": "Social Fulfillment",
    "question": "Felt socially fulfilled?",
    "internal_name": "social-fulfillment",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 122,
    "title": "Fever",
    "question": "Experiencing a fever?",
    "internal_name": "fever",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 123,
    "title": "Conception",
    "question": "Trying to conceive?",
    "internal_name": "conception",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 124,
    "title": "Perimenopause",
    "question": "Experiencing symptoms of perimenopause?",
    "internal_name": "perimenopause",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 125,
    "title": "Postmenopause",
    "question": "Experiencing symptoms of postmenopause?",
    "internal_name": "postmenopause",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 126,
    "title": "Recovery",
    "question": "Felt recovered?",
    "internal_name": "recovery",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 127,
    "title": "Compression Therapy",
    "question": "Did compression therapy?",
    "internal_name": "compression-therapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 128,
    "title": "Luteinizing Hormone (LH) Test",
    "question": "Took a Luteinizing hormone test?",
    "internal_name": "luteinizing-hormone-test",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 129,
    "title": "Radiation Therapy",
    "question": "Received radiation therapy?",
    "internal_name": "radiation-therapy",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 130,
    "title": "Make Progress",
    "question": "Made progress on an important goal?",
    "internal_name": "make-progress",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 131,
    "title": "Learning",
    "question": "Learned something interesting or important?",
    "internal_name": "learning",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 132,
    "title": "Family and Friends",
    "question": "Connected with family and/or friends?",
    "internal_name": "family-and-friends",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 133,
    "title": "Spirituality",
    "question": "Engaged in spiritual practice?",
    "internal_name": "spirituality",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 134,
    "title": "AD(H)D Medication",
    "question": "Took AD(H)D medication?",
    "internal_name": "adhd-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 135,
    "title": "Anxiety",
    "question": "Felt nervous or anxious?",
    "internal_name": "anxiety",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 136,
    "title": "Positivity",
    "question": "Feel generally positive about the future?",
    "internal_name": "positivity",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 137,
    "title": "Depression",
    "question": "Felt depressed or down?",
    "internal_name": "depression",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 138,
    "title": "Morning Sunlight",
    "question": "Saw direct sunlight upon waking up?",
    "internal_name": "morning-sunlight",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 139,
    "title": "Artificial Light",
    "question": "Saw artificial light upon waking up?",
    "internal_name": "artificial-light",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 140,
    "title": "Sunset",
    "question": "Watched the sunset?",
    "internal_name": "sunset",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 141,
    "title": "Snacking",
    "question": "Snacked in between meals?",
    "internal_name": "snacking",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 142,
    "title": "Dim lights",
    "question": "Dimmed your lights after sunset?",
    "internal_name": "dim-lights",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 143,
    "title": "Daylight Eating",
    "question": "Ate all your meals during daylight hours?",
    "internal_name": "daylight-eating",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 144,
    "title": "Monkeypox Symptoms",
    "question": "Experiencing monkeypox symptoms?",
    "internal_name": "monkeypox-symptoms",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 145,
    "title": "Calories",
    "question": "Tracked your calories?",
    "internal_name": "calories",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 152,
    "title": "Vacation",
    "question": "Took a vacation day?",
    "internal_name": "vacation",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 155,
    "title": "Cold Shower",
    "question": "Took a cold shower?",
    "internal_name": "cold-shower",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 157,
    "title": "Hot Tub",
    "question": "Spent time in a hot tub?",
    "internal_name": "hot-tub",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 158,
    "title": "Zinc",
    "question": "Took a zinc supplement?",
    "internal_name": "zinc",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 159,
    "title": "Calcium Supplement",
    "question": "Took a calcium supplement?",
    "internal_name": "calcium-supplement",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 163,
    "title": "Zone 2 Cardio",
    "question": "Did Zone 2 cardio?",
    "internal_name": "zone-2-cardio",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 164,
    "title": "Mouth Tape",
    "question": "Wore mouth tape while sleeping?",
    "internal_name": "mouth-tape",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 165,
    "title": "Blue-Light Blocking Glasses (WHOOP Evening Lenses)",
    "question": "Wore blue-light blocking glasses (WHOOP Evening Lenses)",
    "internal_name": "blue-light-blocking-glasses-whoop-evening",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 166,
    "title": "Blue-Light Blocking Glasses (WHOOP All-Day Lenses)",
    "question": "Wore blue-light blocking glasses (WHOOP All-Day Lenses)?",
    "internal_name": "blue-light-blocking-glasses-whoop-all-day",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 167,
    "title": "Sodium",
    "question": "Consumed sodium?",
    "internal_name": "sodium",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 168,
    "title": "Fiber",
    "question": "Consumed fiber?",
    "internal_name": "fiber",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 169,
    "title": "Magnesium",
    "question": "Consumed magnesium?",
    "internal_name": "magnesium",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 170,
    "title": "Calcium",
    "question": "Consumed calcium?",
    "internal_name": "calcium",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 172,
    "title": "Parenting Sick Child",
    "question": "Parenting a sick child?",
    "internal_name": "parenting-sick-child",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 174,
    "title": "Sleep in Dark Room",
    "question": "Slept in a dark room?",
    "internal_name": "sleep-in-dark-room",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 175,
    "title": "Weight-Loss Medication",
    "question": "Took weight-loss medication?",
    "internal_name": "weight-loss-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 177,
    "title": "Headache",
    "question": "Experienced a headache?",
    "internal_name": "headache",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 178,
    "title": "Migraine",
    "question": "Experienced a migraine?",
    "internal_name": "migraine",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 179,
    "title": "Hot Shower Before Bed",
    "question": "Took a hot shower before bed?",
    "internal_name": "hot-shower-before-bed",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 180,
    "title": "Mouthguard",
    "question": "Wore a mouthguard while sleeping?",
    "internal_name": "mouthguard",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 181,
    "title": "AG1 - Foundational Nutritional Supplement",
    "question": "Did you drink AG1?",
    "internal_name": "ag1",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 184,
    "title": "Pumping",
    "question": "Breast milk pumping?",
    "internal_name": "pumping",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 185,
    "title": "Prenatal Vitamins",
    "question": "Took prenatal supplement(s)?",
    "internal_name": "prenatal-vitamins",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 186,
    "title": "Feeding Baby at Night",
    "question": "Woke up for a nighttime feed?",
    "internal_name": "feeding-baby-at-night",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 187,
    "title": "Postnatal Vitamins",
    "question": "Took postnatal supplement(s)?",
    "internal_name": "postnatal-vitamins",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 196,
    "title": "Shared Bedroom With Child",
    "question": "Shared a sleeping space with a child?",
    "internal_name": "shared-bedroom-with-child",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 202,
    "title": "Electrolytes",
    "question": "Took electrolyte supplements?",
    "internal_name": "electrolytes",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 203,
    "title": "GLP-1",
    "question": "Took a GLP-1?",
    "internal_name": "glp-1",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 204,
    "title": "Ketamine",
    "question": "Took Ketamine?",
    "internal_name": "ketamine",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 205,
    "title": "LSD",
    "question": "Took LSD (lysergic acid diethylamide)?",
    "internal_name": "lsd",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 206,
    "title": "Psilocybin",
    "question": "Took Psilocybin (Magic Mushrooms)?",
    "internal_name": "psilocybin",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 207,
    "title": "Nicotine",
    "question": "Consumed nicotine?",
    "internal_name": "nicotine",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 208,
    "title": "Threat",
    "question": "Faced threats?",
    "internal_name": "threat",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 209,
    "title": "Challenge",
    "question": "Faced challenges?",
    "internal_name": "challenge",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 210,
    "title": "Acne",
    "question": "Experienced acne?",
    "internal_name": "acne",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 211,
    "title": "Fatigue",
    "question": "Experienced fatigue?",
    "internal_name": "fatigue",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 212,
    "title": "Breast Growth",
    "question": "Noticed breast growth?",
    "internal_name": "breast-growth",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 214,
    "title": "Muscle/Body Aches",
    "question": "Experienced muscle or body aches?",
    "internal_name": "muscle/body-aches",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 215,
    "title": "Back Pain",
    "question": "Experienced back pain?",
    "internal_name": "back-pain",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 216,
    "title": "Heartburn",
    "question": "Experienced heartburn?",
    "internal_name": "heartburn",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 217,
    "title": "Gas",
    "question": "Experienced excessive gas?",
    "internal_name": "gas",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 218,
    "title": "Constipation",
    "question": "Experienced constipation?",
    "internal_name": "constipation",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 219,
    "title": "Vomiting",
    "question": "Experienced vomiting?",
    "internal_name": "vomiting",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 220,
    "title": "Food Cravings",
    "question": "Experienced food cravings?",
    "internal_name": "food-cravings",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 221,
    "title": "Brain Fog",
    "question": "Experienced brain fog?",
    "internal_name": "brain-fog",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 222,
    "title": "Vaginal Spotting",
    "question": "Noticed vaginal spotting?",
    "internal_name": "vaginal-spotting",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 223,
    "title": "Vaginal Discharge - Creamy",
    "question": "Noticed vaginal discharge is creamy?",
    "internal_name": "vaginal-discharge---creamy",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 224,
    "title": "Vaginal Discharge - Egg White",
    "question": "Noticed vaginal discharge has egg white consistency?",
    "internal_name": "vaginal-discharge---egg-white",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 225,
    "title": "Vaginal Discharge - Grey",
    "question": "Noticed vaginal discharge is grey?",
    "internal_name": "vaginal-discharge---grey",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 226,
    "title": "Vaginal Discharge - Sticky",
    "question": "Noticed vaginal discharge is sticky?",
    "internal_name": "vaginal-discharge---sticky",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 227,
    "title": "Vaginal Dryness",
    "question": "Experienced vaginal dryness?",
    "internal_name": "vaginal-dryness",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 228,
    "title": "Increased Libido",
    "question": "Experienced increased libido?",
    "internal_name": "increased-libido",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 229,
    "title": "Decreased Libido",
    "question": "Experienced decreased libido?",
    "internal_name": "decreased-libido",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 230,
    "title": "Mood Swings",
    "question": "Experienced mood swings?",
    "internal_name": "mood-swings",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 231,
    "title": "Pelvic Pain",
    "question": "Experienced pelvic pain?",
    "internal_name": "pelvic-pain",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 232,
    "title": "Hot Flashes During the Day",
    "question": "Experienced hot flashes during the day?",
    "internal_name": "hot-flashes-during-day",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 233,
    "title": "Temperature Sensitivity",
    "question": "Felt unusually sensitive to temperature changes?",
    "internal_name": "temperature-sensitivity",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 235,
    "title": "Night Sweats",
    "question": "Noticed night sweats disrupting sleep?",
    "internal_name": "night-sweats",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 236,
    "title": "Forgetfulness",
    "question": "Experienced memory lapses or forgetfulness?",
    "internal_name": "forgetfulness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 237,
    "title": "Sleep Quality Decline",
    "question": "Experienced reduced sleep quality due to menopausal symptoms?",
    "internal_name": "sleep-quality-decline",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 238,
    "title": "Painful Intercourse",
    "question": "Had discomfort or pain during intercourse?",
    "internal_name": "painful-intercourse",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 239,
    "title": "Urinary Symptoms",
    "question": "Experienced urinary symptoms (e.g., urgency or incontinence)?",
    "internal_name": "urinary-symptoms",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 240,
    "title": "Joint Pain or Stiffness",
    "question": "Experienced joint pain or stiffness?",
    "internal_name": "joint-pain-or-stiffness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 241,
    "title": "Hair Thinning/Loss",
    "question": "Noticed thinning hair or hair loss?",
    "internal_name": "hair-thinning-loss",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 242,
    "title": "Skin Changes",
    "question": "Noticed skin changes, like dryness or sensitivity?",
    "internal_name": "skin-changes",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 243,
    "title": "Breast Tenderness",
    "question": "Experienced breast tenderness?",
    "internal_name": "breast-tenderness",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 244,
    "title": "Heart Palpitations",
    "question": "Experienced heart palpitations today?",
    "internal_name": "heart-palpitations",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 245,
    "title": "Body Odor Changes",
    "question": "Noticed changes in body odor today?",
    "internal_name": "body-odor-changes",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 246,
    "title": "Tingling / Numbness",
    "question": "Experienced tingling or numbness in extremities?",
    "internal_name": "tingling-numbness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 247,
    "title": "Dizzy / Lightheadedness",
    "question": "Felt dizzy or lightheaded today?",
    "internal_name": "dizzy-lightheadedness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 248,
    "title": "Cycle Irregularity",
    "question": "Experienced cycle irregularity or missed periods?",
    "internal_name": "cycle-irregularity",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 249,
    "title": "HRT",
    "question": "Used combination hormone replacement therapy (HRT)?",
    "internal_name": "hrt",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 250,
    "title": "Progesterone",
    "question": "Took progesterone supplements or injections?",
    "internal_name": "progesterone",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 251,
    "title": "Progesterone Creams",
    "question": "Took over-the-counter progesterone creams?",
    "internal_name": "progesterone-creams",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 252,
    "title": "Estrogen",
    "question": "Took estrogen-only supplements or patches?",
    "internal_name": "estrogen",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 253,
    "title": "Vaginal Estrogen Cream",
    "question": "Used vaginal estrogen creams?",
    "internal_name": "vaginal-estrogen-cream",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 254,
    "title": "Vaginal Estrogen Rings",
    "question": "Used vaginal estrogen rings?",
    "internal_name": "vaginal-estrogen-rings",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 255,
    "title": "Vaginal Estrogen Tablets",
    "question": "Used vaginal estrogen tablets?",
    "internal_name": "vaginal-estrogen-tablets",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 256,
    "title": "Testosterone Supplements",
    "question": "Took testosterone supplements?",
    "internal_name": "testosterone-supplements",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 257,
    "title": "Anti-Androgen",
    "question": "Took anti-androgen medication (e.g., Spironolactone)?",
    "internal_name": "anti-androgen",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 258,
    "title": "Testosterone Gel/Cream",
    "question": "Used testosterone gel or cream?",
    "internal_name": "testosterone-gel-cream",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 259,
    "title": "Gabapentin",
    "question": "Used gabapentin for menopausal symptoms?",
    "internal_name": "gabapentin",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 260,
    "title": "Clonidine",
    "question": "Used clonidine for menopausal symptoms, e.g. hot flashes?",
    "internal_name": "clonidine",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 261,
    "title": "Thyroid Medication",
    "question": "Took thyroid medication to manage hormonal imbalances?",
    "internal_name": "thyroid-medication",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 262,
    "title": "DHEA",
    "question": "Took DHEA supplements for adrenal support?",
    "internal_name": "dhea",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 263,
    "title": "Allergy Medication",
    "question": "Took allergy medication?",
    "internal_name": "allergy-medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 264,
    "title": "Nightmare",
    "question": "Had a nightmare?",
    "internal_name": "nightmare",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 265,
    "title": "Ashwaganda",
    "question": "Took ashwaganda?",
    "internal_name": "ashwaganda",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 266,
    "title": "Socially drained",
    "question": "Felt socially drained?",
    "internal_name": "socially-drained",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 267,
    "title": "Lunch ",
    "question": "Ate lunch?",
    "internal_name": "lunch",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 268,
    "title": "Dinner ",
    "question": "Ate dinner?",
    "internal_name": "dinner",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 269,
    "title": "Breakfast ",
    "question": "Ate breakfast?",
    "internal_name": "breakfast",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 270,
    "title": "Morning Snack ",
    "question": "Ate a morning snack?",
    "internal_name": "morning-snack",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 271,
    "title": "Afternoon Snack ",
    "question": "Ate an afternoon snack?",
    "internal_name": "afternoon-snack",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 272,
    "title": "Evening Snack ",
    "question": "Ate an evening snack?",
    "internal_name": "evening-snack",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 273,
    "title": "Solo time",
    "question": "Had some solo time?",
    "internal_name": "solo-time",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 274,
    "title": "Plant-based protein",
    "question": "Ate plant-based protein?",
    "internal_name": "plant-based-protein",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 275,
    "title": "Restaurant",
    "question": "Ate at a restaurant?",
    "internal_name": "restaurant",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 276,
    "title": "Home-cooked",
    "question": "Ate home-cooked food?",
    "internal_name": "home-cooked",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 277,
    "title": "Takeout",
    "question": "Ate takeout?",
    "internal_name": "takeout",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 278,
    "title": "Warm Bath",
    "question": "Took a warm bath?",
    "internal_name": "warm-bath",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 295,
    "title": "Standing Desk",
    "question": "Used standing desk?",
    "internal_name": "standing-desk",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 296,
    "title": "Vagus nerve stimulation",
    "question": "Used device for vagus nerve stimulation?",
    "internal_name": "vagus-nerve-stimulation",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 297,
    "title": "Herbal Tea",
    "question": "Drank herbal tea?",
    "internal_name": "herbal-tea",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 298,
    "title": "Post meal walk",
    "question": "Walked after a meal?",
    "internal_name": "post-meal-walk",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 299,
    "title": "Snoring (Partner)",
    "question": "Did your partner snore?",
    "internal_name": "snoring-partner",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 300,
    "title": "Chicken/Poultry",
    "question": "Consumed chicken/poultry?",
    "internal_name": "chicken-poultry",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 301,
    "title": "Beans",
    "question": "Consumed beans?",
    "internal_name": "beans",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 302,
    "title": "Tofu ",
    "question": "Consumed tofu?",
    "internal_name": "tofu",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 303,
    "title": "Nuts",
    "question": "Consumed nuts?",
    "internal_name": "nuts",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 304,
    "title": "Ate before workout",
    "question": "Ate before workout?",
    "internal_name": "ate-before-workout",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 305,
    "title": "Omega 3 Supplement",
    "question": "Took omega 3 supplement?",
    "internal_name": "omega-3-supplement",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 333,
    "title": "Bowel Movements",
    "question": "Experienced bowel movements?",
    "internal_name": "bowel_movements",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 334,
    "title": "SSRI Medication",
    "question": "Took SSRI medication?",
    "internal_name": "ssri_medication",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 336,
    "title": "Beta Blockers",
    "question": "Took beta blocking medication?",
    "internal_name": "beta_blockers",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 338,
    "title": "Accutane",
    "question": "Took Accutane?",
    "internal_name": "accutane",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 339,
    "title": "Ivabradine",
    "question": "Took Ivabradine?",
    "internal_name": "ivabradine",
    "category": "Drugs & Medication",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 340,
    "title": "Iron",
    "question": "Took Iron supplements?",
    "internal_name": "iron",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 341,
    "title": "Valerian",
    "question": "Took Valerian supplement for sleep?",
    "internal_name": "valerian",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 342,
    "title": "Tart Cherry Juice",
    "question": "Drank tart cherry juice?",
    "internal_name": "tart_cherry_juice",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 343,
    "title": "L-theanine",
    "question": "Took L-theanine supplements?",
    "internal_name": "l-theanine",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 344,
    "title": "Rhodiola Rosea",
    "question": "Took rhodiola rosea extract?",
    "internal_name": "rhodiola_rosea",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 346,
    "title": "Alpha-lipoic acid (ALA) supplement",
    "question": "Took Alpha-lipoic acid (ALA) supplements?",
    "internal_name": "alpha_lipoic_acid",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 347,
    "title": "Levothyroxine",
    "question": "Took Levothyroxine medication?",
    "internal_name": "levothyroxine",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 348,
    "title": "Tinnitus",
    "question": "Experienced Tinnitus?",
    "internal_name": "tinnitus",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 349,
    "title": "Video Games",
    "question": "Played video games?",
    "internal_name": "video_games",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 350,
    "title": "Car or Train travel",
    "question": "Travelled in a car or train?",
    "internal_name": "car_or_train_travel",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 351,
    "title": "Social Media",
    "question": "Used social media?",
    "internal_name": "social_media",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 352,
    "title": "Relationship Stress",
    "question": "Experienced stress in a relationship?",
    "internal_name": "relationship_stress",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 353,
    "title": "Grounding or Earthing",
    "question": "Practiced grounding or earthing?",
    "internal_name": "grounding_or_earthing",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 354,
    "title": "Foam Roller",
    "question": "Used a foam roller for muscle tension?",
    "internal_name": "foam_roller",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 355,
    "title": "Inversion Table",
    "question": "Used an inversion table?",
    "internal_name": "inversion_table",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 356,
    "title": "Percussive Massage",
    "question": "Used a percussive massager (e.g., Hypervolt, Theragun)?",
    "internal_name": "percussive_massage",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 357,
    "title": "Contrast Therapy",
    "question": "Practiced contrast therapy (hot/cold)?",
    "internal_name": "contrast_therapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 358,
    "title": "Infrared PEMF Mat",
    "question": "Used an infrared PEMF Mat?",
    "internal_name": "infrared_pemf_mat",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 359,
    "title": "Sound bath",
    "question": "Participated in a sound bath?",
    "internal_name": "sound_bath",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 360,
    "title": "Cooling Pad",
    "question": "Used a cooling pad for muscle recovery?",
    "internal_name": "cooling_pad",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 361,
    "title": "Heating Pad",
    "question": "Used a heating pad for muscle recovery?",
    "internal_name": "heating_pad",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 362,
    "title": "Sleep Disruption",
    "question": "Experienced a sleep disruption?",
    "internal_name": "sleep_disruption",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 363,
    "title": "Soreness",
    "question": "Experienced muscle soreness?",
    "internal_name": "soreness",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 364,
    "title": "Congestion",
    "question": "Felt congested?",
    "internal_name": "congestion",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 365,
    "title": "Indigestion",
    "question": "Experienced indigestion?",
    "internal_name": "indigestion",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 366,
    "title": "Dialysis",
    "question": "Received dialysis treatment?",
    "internal_name": "dialysis",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 367,
    "title": "Concussion",
    "question": "Felt concussed?",
    "internal_name": "concussion",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 368,
    "title": "Food Sensitivity",
    "question": "Experienced food sensitivity?",
    "internal_name": "food_sensistivity",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 369,
    "title": "Blood Donation",
    "question": "Donated blood?",
    "internal_name": "blood_donation",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 370,
    "title": "Plasma Donation",
    "question": "Donated plasma?",
    "internal_name": "plasma_donation",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 371,
    "title": "Platelet Donation",
    "question": "Donated platelets?",
    "internal_name": "platelet_donation",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 372,
    "title": "Camping",
    "question": "Camped outdoors?",
    "internal_name": "camping",
    "category": "Lifestyle",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 374,
    "title": "Loneliness",
    "question": "Experienced loneliness?",
    "internal_name": "loneliness",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 375,
    "title": "Halal Diet",
    "question": "Following a Halal diet?",
    "internal_name": "halal_diet",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 376,
    "title": "Rest Day",
    "question": "Took a rest day?",
    "internal_name": "rest_day",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 377,
    "title": "Epsom Salt Bath",
    "question": "Took a bath with epsom salts?",
    "internal_name": "epsom_salt_bath",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 378,
    "title": "Grounding Sheet",
    "question": "Slept with a grounding or earthing sheet?",
    "internal_name": "grounding_sheet",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 379,
    "title": "Aromatherapy",
    "question": "Used aromatherapy/essential oils for relaxation?",
    "internal_name": "aromatherapy",
    "category": "Recovery",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 381,
    "title": "Child in Bedroom",
    "question": "Slept with a child in your bedroom?",
    "internal_name": "child_in_bedroom",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 382,
    "title": "Nightguard or Retainer",
    "question": "Slept with a nightguard or retainer?",
    "internal_name": "nightguard_or_retainer",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 383,
    "title": "Loud Sleep environment",
    "question": "Slept in a loud environment?",
    "internal_name": "loud_sleep_environment",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 384,
    "title": "Adaptogen Mushrooms",
    "question": "Took adaptogen mushrooms?",
    "internal_name": "adaptogen_mushrooms",
    "category": "Supplements",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 385,
    "title": "Body Pillow",
    "question": "Used a body pillow?",
    "internal_name": "body_pillow",
    "category": "Sleep & Circadian Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 386,
    "title": "Flow State",
    "question": "Experienced flow state?",
    "internal_name": "flow_state",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 387,
    "title": "Dark Chocolate",
    "question": "Consumed dark chocolate?",
    "internal_name": "dark_chocolate",
    "category": "Nutrition",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 388,
    "title": "Chills",
    "question": "Experienced chills?",
    "internal_name": "chills",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 389,
    "title": "Diarrhea",
    "question": "Experienced diarrhea?",
    "internal_name": "diarrhea",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 390,
    "title": "Dry Skin",
    "question": "Is your skin drier than usual?",
    "internal_name": "dry_skin",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 391,
    "title": "Nausea",
    "question": "Experienced nausea?",
    "internal_name": "nausea",
    "category": "Health & Symptoms",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 392,
    "title": "Overwhelm",
    "question": "Feeling overwhelmed?",
    "internal_name": "overwhelm",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 393,
    "title": "Reduced Motivation",
    "question": "Experienced reduced motivation?",
    "internal_name": "reduced_motivation",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 394,
    "title": "Social Withdrawal",
    "question": "Experienced social withdrawal?",
    "internal_name": "social_withdrawal",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 395,
    "title": "Trouble Concentrating",
    "question": "Having trouble concentrating?",
    "internal_name": "trouble_concentrating",
    "category": "Mental Wellbeing",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 396,
    "title": "Vaginal Discharge - Watery",
    "question": "Noticed vaginal discharge is watery?",
    "internal_name": "vaginal-discharge---watery",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 397,
    "title": "Cervical Mucus: Pink, Brown, or Tan",
    "question": "Is your cervical mucus pink, brown, or tan?",
    "internal_name": "cervical_mucus_pink_brown_or_tan",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  },
  {
    "behavior_tracker_id": 398,
    "title": "No Menstrual Flow",
    "question": "Experienced period but no menstrual flow?",
    "internal_name": "no_menstrual_flow",
    "category": "Hormonal Health",
    "magnitude": "bare",
    "status": "active"
  }
] as const;

export const BEHAVIORS_BY_ID = new Map<number, JournalBehavior>(
  BEHAVIORS.map((b) => [b.behavior_tracker_id, b]),
);
export const BEHAVIORS_BY_NAME = new Map<string, JournalBehavior>(
  BEHAVIORS.map((b) => [b.internal_name, b]),
);
